import { GoogleGenerativeAI, FunctionDeclaration, SchemaType } from "@google/generative-ai";
import OpenAI from "openai";
import * as dotenv from "dotenv";

dotenv.config();

export interface DraftPrdInput {
    proposal: string;
    impact_report: string; // the JSON stringified report from simulate_impact
}

export interface DraftPrdResult {
    prd_markdown: string;
}

export const draftPrdDeclaration: FunctionDeclaration = {
    name: "draft_prd",
    description: "Generates a fully-formatted, detailed Draft PRD (Product Requirements Document) based on the user's initial proposal and the feasibility Sandbox Impact Report. ALWAYS use this AFTER running simulate_impact.",
    parameters: {
        type: SchemaType.OBJECT,
        properties: {
            proposal: {
                type: SchemaType.STRING,
                description: "The original feature proposal."
            },
            impact_report: {
                type: SchemaType.STRING,
                description: "The JSON string output generated by the simulate_impact tool."
            }
        },
        required: ["proposal", "impact_report"]
    }
};

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
const geminiModel = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });

const openai = new OpenAI({
    apiKey: process.env.DASHSCOPE_API_KEY || "sk-dummy",
    baseURL: process.env.OPENAI_BASE_URL || "https://dashscope.aliyuncs.com/compatible-mode/v1"
});

async function getProvider(): Promise<string> {
    try {
        const res = await fetch("http://localhost:8001/api/settings");
        if (res.ok) {
            const data = await res.json();
            return data.llm_provider || "gemini";
        }
    } catch (e) {
        console.warn("Could not fetch provider, defaulting to gemini");
    }
    return "gemini";
}

export async function draftPrd(input: DraftPrdInput): Promise<DraftPrdResult> {
    const { proposal, impact_report } = input;
    const provider = await getProvider();

    const prompt = `
    You are 'Nexis', a Senior Business Architect and Product Manager.
    Your task is to take a PM's raw idea and the automated System Impact Report, and generate a highly structured, professional Draft PRD in GitHub-flavored Markdown.

    === Proposal ===
    ${proposal}

    === Sandbox Impact Report ===
    ${impact_report}
    
    === PRD Generation Instructions ===
    Generate a complete PRD following this exact structure:
    # 📝 Draft PRD: [Auto-generate an elegant title]
    
    ## 1. Background & Objective
    [Explain the business intent behind the proposal]
    
    ## 2. Feasibility & Risk Assessment
    [Summarize the is_feasible flag, and document the broken_rules and suggestions from the impact report. Call out high risks.]
    
    ## 3. Affected System Modules
    [List the affected_modules. Use bullet points.]
    
    ## 4. Required Data/Field Changes
    [List the missing_fields that need to be added to the database or API interfaces.]
    
    ## 5. Functional Requirements
    [Draft detailed, step-by-step business rules and system behaviors required to implement the proposal. Be explicit.]
    
    Output ONLY the markdown content. Do not wrap in JSON or add any conversational prefixes.
    `;

    try {
        let text = "";

        if (provider.includes("qwen") || provider.includes("gpt")) {
            const completion = await openai.chat.completions.create({
                model: provider,
                messages: [{ role: "user", content: prompt }]
            });
            text = completion.choices[0].message.content || "";
        } else {
            const result = await geminiModel.generateContent(prompt);
            text = result.response.text();
        }

        return { prd_markdown: text.trim().replace(/^```markdown/g, '').replace(/```$/g, '').trim() };

    } catch (e) {
        console.error("PRD Drafter LLM (" + provider + ") Failed:", e);
        return {
            prd_markdown: "# Error Generating PRD\nInternal system error: " + (e as Error).message
        };
    }
}
